"""Saude do servico e coerencia entre models e migrations."""

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected


def test_health_e_liveness_puro(client):
    """Nao toca o banco: uma piscada de conexao nao pode tirar o servico do
    balanceador."""
    r = client.get("/health")
    assert r.status_code == 200
    assert r.json() == {"status": "ok"}


def test_health_db_confirma_o_banco(client):
    r = client.get("/health/db")
    assert r.status_code == 200
    assert r.json()["banco"] == "ok"


def test_migration_nao_derivou_dos_models(schema):
    """alembic check com compare_type e compare_server_default.

    Sem este teste, alguem muda um model, esquece a migration, os testes
    continuam verdes (porque o schema de teste tambem sai dos models) e o
    deploy quebra em producao.
    """
    # command.check levanta AutogenerateDiffsDetected quando ha diferenca;
    # passar sem excecao e a prova de que migration e models batem.
    command.check(Config("alembic.ini"))


def test_openapi_documenta_o_200_de_duplicada(client):
    """O OpenAPI precisa contar os dois desfechos do POST.

    Quem escreve o firmware le isto para saber que 200 tambem e sucesso.
    """
    esquema = client.get("/openapi.json").json()
    respostas = esquema["paths"]["/api/viagens"]["post"]["responses"]
    assert set(respostas) >= {"200", "201", "404", "422"}
