"""estrutura inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-05 21:46:21.772303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretaria',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('carro',
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('numero_frota', sa.String(length=30), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('dispositivo_id', sa.String(length=60), nullable=False),
    sa.Column('secretaria_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_carro_dispositivo_id'), 'carro', ['dispositivo_id'], unique=True)
    op.create_index('ix_carro_secretaria_id', 'carro', ['secretaria_id'], unique=False)
    op.create_table('servidor',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('secretaria_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('viagem',
    sa.Column('carro_id', sa.Uuid(), nullable=False),
    sa.Column('servidor_id', sa.Uuid(), nullable=True),
    sa.Column('lote_id', sa.String(length=64), nullable=False),
    sa.Column('placa_informada', sa.String(length=10), nullable=True),
    sa.Column('rota', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('km_gps', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qtd_pontos', sa.Integer(), nullable=False),
    sa.Column('qtd_pontos_recebidos', sa.Integer(), nullable=False),
    sa.Column('versao_calculo', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('odometro_inicio', sa.Integer(), nullable=True),
    sa.Column('odometro_fim', sa.Integer(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recebida_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['carro_id'], ['carro.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carro_id', 'lote_id', name='uq_viagem_carro_lote')
    )
    op.create_index('ix_viagem_carro_inicio', 'viagem', ['carro_id', 'inicio'], unique=False)
    op.create_index('ix_viagem_inicio', 'viagem', ['inicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_viagem_inicio', table_name='viagem')
    op.drop_index('ix_viagem_carro_inicio', table_name='viagem')
    op.drop_table('viagem')
    op.drop_table('servidor')
    op.drop_index('ix_carro_secretaria_id', table_name='carro')
    op.drop_index(op.f('ix_carro_dispositivo_id'), table_name='carro')
    op.drop_table('carro')
    op.drop_table('secretaria')
    # ### end Alembic commands ###
